# Generated by Django 3.1.1 on 2021-01-11 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mirna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MirnaFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.mirna')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='impact_factor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.AddField(
            model_name='sentence',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search_engine.article'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='cancer',
            field=models.ManyToManyField(to='search_engine.Cancer'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='mirna',
            field=models.ManyToManyField(to='search_engine.MirnaFamily'),
        ),
    ]
