# Generated by Django 3.1.1 on 2021-01-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0002_auto_20210111_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='impact_factor',
            field=models.FloatField(),
        ),
    ]
