# Generated by Django 3.1.1 on 2021-01-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0003_auto_20210111_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cancer',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='mirna',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
